# Generated by Django 4.2.1 on 2023-05-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=12345678901, max_length=11),
            preserve_default=False,
        ),
    ]
